services:
  - type: web
    name: comparador-docx-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
